Allow geodataframes in assert_polygons
earthlab/matplotcheck pull request #188
Opened 2020-02-06 21:18 UTC by nkorinek

Simple fix to allow `GeoDataFrames` to be valid inputs into `assert_polygons`. Also fixed issue with check that input wasn't empty.

2020-02-06 21:18 UTC, nkorinek commented
@lwasser

2020-02-07 20:02 UTC, lwasser commented on matplotcheck/vector.py
>  		polygons_expected: list of polygons expected to be founds on Axes ax
@nkorinek please make sure each input parameter uses numpy style docs. so this should have the expected input type and then on the second line, the explanation of what that object is / does. please follow earthpy so we may need to update many of the docstrings.

2020-02-07 20:03 UTC, lwasser requested changes
@nkorinek  great start!! given you are working on the vector module. let's start working on tests for it too. So when you submit new functionality please also include tests for the method that you worked on. i'll wait to merge this until you have added some tests. also please update the change log like we do in earthpy each time.

2020-02-10 18:47 UTC, nkorinek commented
@lwasser added changes requested!

2020-02-10 20:38 UTC, nkorinek commented
Build is failing due to issues with descartes

2020-02-11 02:19 UTC, lwasser commented
ahhh @nkorinek i remember running into this before. we could potentially add descartes as a requirement like geopandas does: 

https://github.com/geopandas/geopandas/blob/2d6b78b28bfa8a4457da81d3b8507309bdf91850/requirements.test.txt#L5 

just for testing purposes. and then add language about installing it IF plotting polygons similar to what geopandas has?? This might help us move forward now and then consider dependencies more carefully in the future?

2020-02-11 02:23 UTC, nkorinek commented
@lwasser sounds good! I'll try and be more careful with adding dependencies, I've tried to add a few today!

2020-02-13 00:24 UTC, nkorinek commented
@lwasser finally passing all tests!

2020-02-13 17:34 UTC, lwasser approved these changes

2020-02-13 17:35 UTC, merged