Hist bin midpoints
earthlab/matplotcheck pull request #204
Opened 2020-02-27 19:26 UTC by nkorinek

Added two new functions, `get_bin_midpoints()` and `assert_bin_midpoints()` to the PlotTester object in order to cover testing requested in this issue: https://github.com/earthlab/matplotcheck/issues/184 . Added tests and documentation for these new arguments as well.

2020-03-03 16:32 UTC, lwasser commented
@nkorinek what does this do for us? can you add some example application to our histogram vignette so i can better understand and see how it works? 
https://matplotcheck.readthedocs.io/en/latest/gallery_vignettes/plot_histogram_testing.html#sphx-glr-gallery-vignettes-plot-histogram-testing-py

2020-03-03 19:01 UTC, nkorinek commented
@lwasser I added the functionality to the histogram vignette to clarify what it does. As far as what it does for us, I believe it adds the functionality that was requested in this issue https://github.com/earthlab/matplotcheck/issues/184 If I misunderstood the issue and this is not what you were looking for please let me know so I can change course!

2020-03-19 22:22 UTC, lwasser commented on examples/plot_histogram_testing.py
> +# For this example, we will create a plot tester object from a histogram plot,
@nkorinek this is great - will you please consistently use "you" rather than "we"? I prefer you for vignettes and lessons!!

2020-03-19 22:23 UTC, lwasser commented on examples/plot_histogram_testing.py
> +midpoints_plot_hold = nb.convert_axes(plt, which_axes="current")
@nkorinek i'm curious - do you have to use this line? can't you just pass the ax object to `PlotTester()` ?

2020-03-19 22:24 UTC, lwasser commented on examples/plot_histogram_testing.py
> +midpoints_plot_hold = nb.convert_axes(plt, which_axes="current")
this is a notebook call to grab the current axis in a cell. i think we do want a vignette that explains how to use MPC in notebooks but this line is extra. Perhaps you could include this line with a comment that says - this is for notebook applications only. and comment it out ?

2020-03-19 22:25 UTC, lwasser commented on examples/plot_histogram_testing.py
> +# We got the values from the plot tester object! As you can see, the values
Here you use we and you in the same line! let's use "you" everywhere!

2020-03-19 22:25 UTC, lwasser commented on matplotcheck/base.py
> +        """Returns the middle value of each bin in a histogram
How about the "mid point value" of each bin?

2020-03-19 22:27 UTC, lwasser requested changes
@nkorinek just a few small changes to the vignette  and we can merge this. let's save the test cleanup as we discussed on slack for a separate PR!

2020-03-20 16:30 UTC, nkorinek commented
@lwasser changes are in!

2020-03-23 17:02 UTC, lwasser commented on matplotcheck/tests/test_base_data.py
> +        ValueError, match="Bin midpoints lists lengths do no matc"
```suggestion
        ValueError, match="Bin midpoints lists lengths do no match"
```

2020-03-23 17:03 UTC, lwasser approved these changes

2020-03-23 19:51 UTC, nkorinek commented
@lwasser this is passing everything, but appveyor failed and doesn't have a details tab? I haven't seen that before and I'm not sure how to fix it.

2020-03-24 22:35 UTC, lwasser commented
@nkorinek i'm seeing green on everything? where is the error that you're seeing? it seems good to me but please confirm that i'm not missing something. if i'm not we can merge this puppy!!

2020-03-24 22:47 UTC, nkorinek commented
@lwasser it was failing, but it's been fixed now, weird! Looks good to go, I just fixed the CHANGELOG merge conflict.

2020-03-24 23:07 UTC, lwasser commented
great. @nkorinek sometimes appveyor is finicky and just needs to rebuild. i'm not really sure why. but i'll merge this one CI finishes. looks like travis is still going here.

2020-03-26 16:09 UTC, merged