Contributors update
earthlab/matplotcheck pull request #213
Opened 2020-03-07 01:06 UTC by nkorinek

Added a contributors file with the information that was previously stored in the README file.

2020-03-07 01:40 UTC, lwasser commented on CONTRIBUTORS.rst
> +  :alt: Ryan Solvik
oops Laroque (double check my spelling please)

2020-03-07 01:40 UTC, lwasser commented on README.md
> -## Active Contributors
@nkorinek my apologies for not being clear. i want to keep the contributors in the readme so take what you did above and move it down here. i wanted to switch my name to the github image and then add your name below it with your github image as well.

2020-03-07 01:41 UTC, lwasser commented on README.md
> -## Dev Setup (to be moved to contributing)
Then this part moves to contributing .rst as you did

2020-03-07 01:42 UTC, lwasser requested changes

2020-03-07 01:42 UTC, lwasser commented on README.md
> -## Contributors
This part stays in the readme but let's fix ryan's name. i see this was my mistake!! can you help me fix it?

2020-03-07 01:42 UTC, lwasser commented on README.md
> -## How to Contribute
This section how to contribute stays in the readme as well.

2020-03-10 17:02 UTC, nkorinek commented
@lwasser ok I think I fixed it!

2020-03-10 20:41 UTC, lwasser approved these changes

2020-03-10 20:41 UTC, lwasser commented
excellent! thank you @nkorinek merging this!

2020-03-10 20:41 UTC, merged