Autograde tests
earthlab/matplotcheck pull request #224
Opened 2020-03-18 22:40 UTC by nkorinek

Added pytest tests for the autograde module!

2020-03-18 23:10 UTC, nkorinek commented
@lwasser so this is a weird bug that's causing this to fail. For some reason, the tests I wrote for the `autograde` wrapper are causing tests that rely on the pytest fixture `pt_hist` in the file `test_base_data` to fail. It is giving it 106 bins instead of 6 bins. In my new tests, I never touch that fixture or that file at all. If I rename my file so that it is run after `test_base_data`, everything passes. But there should be a more elegant solution than that, right? Any idea what's going on here? Thanks!

2020-03-20 18:13 UTC, nkorinek commented
@lwasser fixed all formatting issues and this is ready for review!

2020-03-20 21:55 UTC, lwasser commented on matplotcheck/tests/test_autograde.py
> +    """Test that a normal test is run with autograder and fails"""
```suggestion
    """Test that a when a test fails, an assertion error is returned"""
```

2020-03-20 21:56 UTC, lwasser commented on matplotcheck/tests/test_autograde.py
> +    """Test that a custom message gets passed into a passed test"""
```suggestion
    """Test that when a custom message is provided, it is correctly returned to the user."""
```

2020-03-20 21:56 UTC, lwasser commented on matplotcheck/tests/test_autograde.py
> +    """Test that a custom message gets passed into a failed test"""
```suggestion
    """Test that a custom message for a failed test gets returned"""
```

2020-03-20 21:57 UTC, lwasser commented on matplotcheck/tests/test_autograde.py
> +    """Test that the output returns the correct points and output"""
```suggestion
    """Test that the correct number of points are returned"""
```

2020-03-20 21:57 UTC, lwasser commented on matplotcheck/tests/test_autograde.py
> +    """Test that the output returns the correct points and output"""
```suggestion
    """Test that the correct points are returned when a test fails"""
```

2020-03-20 21:58 UTC, lwasser requested changes
looking good @nkorinek a few more changes!

2020-03-23 19:46 UTC, nkorinek commented
@lwasser all green on CI

2020-03-24 22:37 UTC, lwasser approved these changes
nice work @nkorinek !!!

2020-03-24 22:37 UTC, merged

2020-03-24 22:38 UTC, lwasser commented
this addressed issue #105