Lines vignette
earthlab/matplotcheck pull request #228
Opened 2020-03-23 20:40 UTC by nkorinek

Vignette to demonstrate line testing capabilities in the `base` package in `matplotcheck`. 

This vignette seems a bit sparse. I left out `assert_xydata` as it was demonstrrated in the `plot_testing_basics` vignette, but I could add it in here as a reminder if we wanted to! Also: I could add in x/y lims assertions in this vignette if we wanted to. I wasn't sure how focused we wanted this vignette to be, so I stuck to the basics and I have tests ready to add if we decide we want more!

2020-03-23 21:10 UTC, nkorinek commented
@lwasser so this vignette is failing due to my use of seaborn to plot the regression line. Seaborn is not part of the CI environment. Do you want me to figure out a way to plot this without seaborn, or would we be able to add it to the environment? I know we've talked about not adding anymore packages to this environment, but thought I'd see what your opinion was. Thanks!

2020-03-24 22:30 UTC, lwasser commented
@nkorinek ahhhhh we can add seaborn to our docs envt. i'm not sure if you can do it here.

https://github.com/earthlab/matplotcheck/blob/master/readthedocs.yml

the easiest would be to use something else. is that an option tho? some tools like geopandas do have a yml file just for read the docs.

2020-04-02 16:16 UTC, lwasser commented
@nkorinek let's keep this simple. let's add seaborn as a dev-requirements item in the list of tools

2020-04-10 20:11 UTC, jlpalomino commented
For our documentation, we have verbally discussed changes that will be completed by nkorinek, including the addition of more explanation about the object type that is being tested (e.g. a story about what kind of data is being used and what the test is actually looking for) both at the top of the notebook and in the comments, and a new section at the bottom of the vignette for additional options when using a Jupyter Notebook implementation.

2020-04-20 20:53 UTC, nkorinek commented
@jlpalomino I'm hunting down a few issues on this branch, I'll ping you when they're ironed out

2020-04-27 21:19 UTC, nkorinek commented
@jlpalomino I fixed the bugs I was seeing. CI is failing due to an unrelated issue and this vignette could use a review now!

2020-04-27 23:15 UTC, jlpalomino requested changes
Great job @nkorinek!  Mostly minor comments regarding wording, but let me know if you have any questions.  Ping me when you are ready for me to review again.  Thanks!

2020-04-27 23:15 UTC, jlpalomino commented on CHANGELOG.md
> +* Added a vignette for line functions (@nkorinek, #155)
Minor comment here - the style for these entries is present tense, so "Add" and "Change/Modify/Update".

2020-04-27 23:15 UTC, jlpalomino commented on matplotcheck/base.py
> +                if (
I assume this change in base.py is something that you and @lwasser discussed.  I will ask her to review this section to verify the changes.

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# You will start by importing the required packages and plotting a creating
Use either "plotting" or "creating" a line plot.

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +import matplotlib.pyplot as plt
Update the order for these imports, per PEP 8: matplotlib, seaborn, numpy, scipy, pandas, matplotcheck

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Before we can grade a plot we have to create example data. This data could be
Change to: "Before we create a plot, we need to create some data.  For plots with regression lines, you will need data in which you are looking for trends over time, such as maximum values from lidar-derived measurements."

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +
Remove blank line after regular comment (i.e. code directly follows comment).

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +to test line plots in Python.
Change to: "to test line plots (including regression lines) in Python."

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Create the data for the line plot
"Create dataframe of data points"

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Plot the points, line of regression, and a one to one line for reference
"Plot data points, regression line, and one-to-one (1:1) line for reference"

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +
Remove blank line between comment and the next code line.

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Setup
Change to: " # Import Packages"

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +
Remove blank line between comment and the next code line.

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Testing the Line Plot
Move this section "Testing the Line Plot" to before line 56, so that the code to create the PlotTester object is within this text section.

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# the line type is a one to one line or a regression line, and you can test
Change to: "that the line type is..."

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# As you can see, there are two line types on this plot. A one to one line for
Change to: "As you can see, there are two line types on this plot: a one-to-one line for reference and a regression line of the data points."

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# (or both types of line) are present in your plot. These are the only types
Add a set of parenthesis around "These are the only...."

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Points and line of regression
Change to: "and regression line"

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Another aspect of a line plot that you can test is the slope and Y intercept,
Change to: "Other aspects of the line plot that you can test are the slope and y intercept to ensure that the line represents the correct values".

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# function in the PlotTester object in order to get the slope and y intercept.
Is the code called like this: ``line_figure_tests.get_slope_yintercept()``?  If so, I would specify that object name as an example, and also change the language of line 85 slightly to be: "method of the PlotTester object, in order to..."

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Create the slope and intercept data for the line in the plot to check against
Change to: "Get slope and y intercept data of regression line for testing"

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Check line is correct
Change to: "Check that slope and y intercept are correct (expected) values"

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# HERE'S WHERE YOU STORE THE PLOT!
Change this text to match [vector vignette](https://github.com/nkorinek/matplotcheck/blob/da924a0e4374b1563120b517ae7a935fb07aa5a5/examples/plot_vector_testing.py): "Here is where you access the axes objects of the plot for testing.
You can add the code line below to the end of any plot cell to store all axes objects created by matplotlib in that cell."

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# This can then be turned into a PlotTester object.
Change this section to match [vector vignette](https://github.com/nkorinek/matplotcheck/blob/da924a0e4374b1563120b517ae7a935fb07aa5a5/examples/plot_vector_testing.py): "This object can then be turned into a PlotTester object."

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Points and line of regression
Change to: "and regression line"

2020-04-27 23:15 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# MatPlotCheck can be used to help grade Jupyter Notebooks as well. The main
Change this text to match [vector vignette](https://github.com/nkorinek/matplotcheck/blob/da924a0e4374b1563120b517ae7a935fb07aa5a5/examples/plot_vector_testing.py): "Matplotcheck can be used to test plots in Jupyter Notebooks as well. The main difference is how you access the axes objects from the plot that you want to test. Below is an example of how you could access the axes of a plot you want to test in a Jupyter Notebook."

2020-04-28 17:33 UTC, nkorinek commented on matplotcheck/base.py
> +                if (
@jlpalomino this is something that @lwasser and I have discussed! It's actually changes from another pull request https://github.com/earthlab/matplotcheck/pull/248 . I thought I had left a comment noting that this branch needs to wait to be merged until #248 is merged, but looking over my comments I may have forgotten to leave one, oops! All changes in base are from that PR.

2020-04-28 17:59 UTC, nkorinek commented
@lwasser this vignette has been updated with the changes suggested by @jlpalomino

2020-04-28 18:45 UTC, jlpalomino requested changes
Thanks @nkorinek A few super small changes, and then I will approve the PR for Leah to do a final review.

2020-04-28 18:45 UTC, jlpalomino commented on examples/plot_line_testing.py
> +These are some examples of using the basic functionality of MatPlotCheck
Minor change here that I missed before: Matplotcheck rather than MatPlotCheck.

2020-04-28 18:45 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# Testing the Line Plot
Minor change here: "Test Line Plots", rather than "Testing the Line Plot"

2020-04-28 18:45 UTC, jlpalomino commented on examples/plot_line_testing.py
> +# First, import the Notebook module from MatPlotCheck
Minor change here that I missed before: Matplotcheck rather than MatPlotCheck.

2020-04-28 20:06 UTC, nkorinek commented
@jlpalomino fixes are in!

2020-04-28 20:49 UTC, jlpalomino approved these changes
Great job @nkorinek! @lwasser This PR is ready for your review.

2020-04-30 20:13 UTC, jlpalomino commented on examples/plot_line_testing.py
> +Testing Line Plots
Oh goodness, missed one. Sorry @nkorinek  This needs a more complete title: "Test Line Plots with Matplotcheck"

2020-04-30 20:26 UTC, nkorinek commented
@jlpalomino title changed!

2020-05-01 00:29 UTC, lwasser commented on examples/plot_line_testing.py
> +# Test Line Plots
```suggestion
# Test Line Plots Using a basic matplotcheck.PlotTester object
```

2020-05-01 00:38 UTC, lwasser commented on examples/plot_line_testing.py
> +# (or both line types) are present in the plot. (NOTE: Regression and 1:1 lines are the only types
@nkorinek i'm confused by this. In theory a line is a line. what does the regression line test actually do that is different from testing any other straight line? i'm just confused by the statement - you can test 1:1 and regression. both are lines so both have slopes and intercepts. are they stored differently in the MPL object? let's just chat a bit so i better understand! can MPC test for any line if there is a slope and intercept given?

2020-05-01 00:40 UTC, lwasser commented on examples/plot_line_testing.py
> +import matplotcheck.base as pt
This is not an ideal import convention `pt`. 

Nathan - let's look into being able to import ANY of the mpc tester objects using
`mpc.RasterTester`, `mpc.VectorTester`, `mpc.PlotTester`

i think we can do this by modifying the init file or similar to what they do in geopandas??

2020-05-01 00:41 UTC, lwasser commented on examples/plot_line_testing.py
> +data = pd.DataFrame(list(zip(col1, col2)), columns=['Data1', 'Data2'])
minor but let's keep all column names lower case so data1 and data2 vs Data1
i like to be consistent with case in code even if it's column names!

2020-05-01 00:42 UTC, lwasser commented on examples/plot_line_testing.py
> +################################################################################
I will look at this when we fix the other imports in a locally build but i'm wondering if this should be a NOTE rather then a section at the bottom of the page. just so it stands out.  what do you think @nkorinek ?

2020-05-01 00:43 UTC, lwasser commented on matplotcheck/base.py
> +                if (
good catch @jlpalomino  :) @nkorinek is making so many changes to this package that there are a lot of outstanding pr's that i need to look at :) and some need to be merged in specific order!

2020-05-01 00:47 UTC, lwasser requested changes
ok @nkorinek i had some questions here related to how we access MPC objects. 
have a look here at Jess's code. i think that we can do something like this to make imports cleaner! 
https://github.com/jhamrick/plotchecker/blob/master/plotchecker/__init__.py

now i know this will result in a need to update our homework tests and vignettes but i think it's worth it. i know there are a few open PR's so let's talk about what order we want to implement this! i'm open to your cleaning this up and then merging it and opening a new issue about imports. or i'm open to implementing this here but we will then need another pr to fix other vignettes. my brain is dead now so i can't decide what is best but you tell me how you'd like to implement this all!! (in what order)

2020-05-01 21:55 UTC, nkorinek reviewed
@lwasser Forgot to leave this comment earlier, sorry! I think it would be best if I opened up a new PR for the import changes and modified this along with the rest of the code in that PR. It makes more sense to me. Let me know if that works!

2020-05-01 21:55 UTC, nkorinek commented on examples/plot_line_testing.py
> +# (or both line types) are present in the plot. (NOTE: Regression and 1:1 lines are the only types
Hey @lwasser! This section became a sort of word soup, so sorry for any confusion. What I'm saying here is that the function `assert_lines_of_type()` can only check if a line is stored as a regression or a 1:1 line. I got that from the docstring describing the `line_types` argument, here: 
```
line_types : list of strings
            Acceptable strings in line_types are as follows
            ``['regression', 'onetoone']``.
```
The code than checks that there's a line which matches the slope/intercept of the line of regression of all points plotted, and/or that there's a line with a slope of 1 and an intercept of 0. That's what I was trying to point out in this section, but I could likely reword it to be more clear.

2020-05-01 21:55 UTC, nkorinek commented on examples/plot_line_testing.py
> +################################################################################
@lwasser this could definitely be a note

2020-05-07 23:20 UTC, nkorinek commented
Update: this now relies on #274 to be merged first

2020-05-13 23:07 UTC, lwasser requested changes
ok @nkorinek a few more things on this vignette . When i build it i see this in the output. i'm just wondering if we use plt.show() in other vignettes as this seems to cause an issue given we have agg settings to ensure CI doesn't get confused. I suspect we don't want to use `plt.show()` in this vignette.

This vignette is making more sense to me. it's not actually a line plot vignette. it's a way to test lines on scatter plots. Given that i think we need a section above the jupyter section that shows the user how to 

1. test the point data on the plot
2. test the x and y axis labels
3. test the plot title.

This can be a fairly simple section but it would be best if people had everything they need to test a scatter plot with those two lines on it in one place. we then may rename the vignette. Take a stab at this and i'll look at it again. 

<img width="788" alt="Screen Shot 2020-05-13 at 5 04 05 PM" src="https://user-images.githubusercontent.com/7649194/81874763-d6593100-953b-11ea-906b-9a5f5db72787.png">

2020-05-14 21:09 UTC, nkorinek commented
@lwasser updated this vignette as per our discussion earlier today. Two important things to note:

1. I ran into a bug with `assert_xydata()` that I've never seen before. It was failing two identical numpy arrays saying that there shapes didn't match. One has a shape of `(15, 1)` while the other had a shape of `(15,)`. So they were the same array, it's just that one was nested inside the other. I fixed this by adding `.flatten()` to the end of the checks to make all of the data checks one dimensional. This will still fail data that doesn't match in length, but fixes this issue. Hope that's ok! 

2. I know we discussed `check-coverage` a lot, however, I found an instance where I think the check should be automatic. Not to say we should take the argument out of the users hands, but when you want to check a regression line and a onetoone line at the same time, it causes issues. You can't set the `check_coverage` to false, as it won't check the coverage of the regression line. However, if you leave it as true than the onetoone line will make the test fail. SO. I think it should be set to `False automatically if the line is a onetoone, but we let users still decide if they want to check coverage on the regression line. Let me know if that makes sense!

2021-01-28 19:50 UTC, closed without merging