Absolute tolerance
earthlab/matplotcheck pull request #234
Opened 2020-03-27 05:36 UTC by ryla5068

This PR adds functionality for absolute tolerance in `base.assert_xydata()` and `base.assert_bin_values()`, addressing issue #157.

2020-04-21 00:03 UTC, lwasser commented on matplotcheck/base.py
> +        tol_rel : float
do you think we need both absolute and relative? it seems like just picking one would keep things simpler. @nkorinek what do you think about this? we are addressing issues for when the data values are decimal places off but pretty much correct. a tolerance would account for that. i just am not sure we need two parameters for it. 1 seems like enough.

2020-04-21 00:04 UTC, lwasser commented on matplotcheck/base.py
> +                rtol=tol_rel,
@ryla5068 is the deal that the numpy allclose function has both parameters so you are exposing them in our method?

2020-04-21 00:05 UTC, lwasser commented on matplotcheck/base.py
> +        if tol_rel > 0 or tol_abs > 0:
once we figure this out it does seem like we should do a quick check to ensure the user provides a reasonable tolerance value. does assert_allclose check that the tolerance value is a number?

2020-04-21 00:07 UTC, lwasser requested changes
a few changes here marty. Can you also please add a changelog update ? and then i just want to talk through relative vs absolute tolerance. i'm not sure we need both. Also what happens if the user provides both by mistake? it seems like picking one might be simplest but perhaps you had a reason for allowing for both?

2020-04-21 00:07 UTC, lwasser commented
oh also please update from master. this PR should then pass CI

2020-04-23 15:40 UTC, lwasser commented
@nkorinek i pinged you on this pr as well. lets plan to focus on this package for the next week to get some of these issues and pr's resolved and merged and such!

2020-04-27 16:13 UTC, lwasser commented on matplotcheck/base.py
> +        tol_rel : float
let's remove relative tolerance and KEEP absolute tolerance which will work with values close to or at 0

2020-04-27 16:15 UTC, lwasser commented
1. please add a change log entry
2. please remove relative tolerance from the method.
3. fix ci ---

2020-04-27 16:16 UTC, lwasser commented
/rebase

2020-05-04 09:02 UTC, ryla5068 commented
@lwasser This PR is failing when building docs. I'm not sure why, and it is not failing for me locally. Other than this, this PR should be ready to merge.

2020-05-07 20:25 UTC, nkorinek commented
@lwasser  this pr has been moved to https://github.com/earthlab/matplotcheck/pull/272

2020-05-07 21:04 UTC, lwasser commented
thank you @nkorinek i will close this pr given it's opened and fixed in a new pr!

2020-05-07 21:04 UTC, closed without merging